name: "Chapter Segments Provider"
guid: "698b6f33-14ca-49b5-9d79-fc3c0ab941f5"
version: 5
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Create media segments based on chapters."
description: >
  Create media segments based on chapters.

category: "General"
artifacts:
  - "Jellyfin.Plugin.ChapterSegments.dll"
changelog: |2-

  ### Dependency updates ###
  - Update mcr.microsoft.com/devcontainers/dotnet Docker tag to v2 (#18) @[renovate[bot]](https://github.com/apps/renovate)
